<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yz</groupId>
        <artifactId>mall-tw-device</artifactId>
        <version>0.0.7-SNAPSHOT</version>
    </parent>
    <artifactId>mall-tw-device-core</artifactId>
    <description>终端管理核心业务</description>
    <dependencies>
        <dependency>
            <groupId>com.yz</groupId>
            <artifactId>mall-tw-device-dao</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.yz</groupId>
            <artifactId>mall-tw-device-interface</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.yz</groupId>
            <artifactId>mall-tw-vehicle-interface</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.yz</groupId>
            <artifactId>mall-auth-interface</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.yz</groupId>
            <artifactId>mall-web</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.yz</groupId>
            <artifactId>mall-redis</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
    </dependencies>
</project>
