
server:
  port: 25002

spring:
  application:
    name: mall-sys
# spring-cloud-alibaba 2023.X版本使用的nacos配置中心
#  config:
#    import:
#      - nacos:middleware.yaml?group=DEFAULT_GROUP&refreshEnabled=true
#      - nacos:sa-token.yaml?group=DEFAULT_GROUP&refreshEnabled=true
#      - nacos:rabbitmq.yaml?group=DEFAULT_GROUP&refreshEnabled=true
#      - nacos:file.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

# MyBatis Mapper SQL 调试包（供 logback-spring.xml 读取）
logging:
  mapper-package: com.yz.mall.sys.mapper
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

xxl:
  job:
    executor:
      appname: ${spring.application.name}
      address: http://192.168.3.20:31004/
      ip: 192.168.3.20
      port: 31004

yz:
  mall:
    sys:
      caffeine-cache:
        enable: true  # 是否启用 Caffeine 本地缓存，默认为 true。设置为 false 时，仅使用 Redis 缓存
        maximum-size: 10000
        expire-after-write: 3600
        expire-after-access: 0
        
rocketmq:
  producer:
    group: producer-mall-sys
  consumer:
    group: consumer-mall-sys
  