
server:
  port: 30004

spring:
  application:
    name: mall-sys

# MyBatis Mapper SQL 调试包（供 logback-spring.xml 读取）
app:
  logging:
    mapper-package: com.yz.mall.sys.mapper
# spring-cloud-alibaba 2023.X版本使用的nacos配置中心
#  config:
#    import:
#      - nacos:middleware.yaml?group=DEFAULT_GROUP&refreshEnabled=true
#      - nacos:sa-token.yaml?group=DEFAULT_GROUP&refreshEnabled=true
#      - nacos:rabbitmq.yaml?group=DEFAULT_GROUP&refreshEnabled=true
#      - nacos:file.yaml?group=DEFAULT_GROUP&refreshEnabled=true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include:  '*'

xxl:
  job:
    executor:
      appname: admin
      address: http://127.0.0.1:31004/
      ip: 127.0.0.1
      port: 31004

yz:
  mall:
    sys:
      caffeine-cache:
        maximum-size: 10000
        expire-after-write: 3600
        expire-after-access: 0
        
rocketmq:
  producer:
    group: producer-mall-sys
  consumer:
    group: consumer-mall-sys
  