server:
  port: 10101

spring:
  application:
    name: mall-kafka-producer

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.3.237:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
