apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: mall
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: yz-mall
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-logs
  namespace: mall
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: yz-mall
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
