apiVersion: v1
kind: Service
metadata:
  name: mall-gateway
  namespace: mall
  labels:
    app.kubernetes.io/name: mall-gateway
spec:
  # 对外入口可再配 Ingress / NodePort；集群内用 ClusterIP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mall-gateway
  ports:
    - name: http
      port: 25001
      targetPort: 25001
