server:
  port: 25005

spring:
  application:
    name: tw-vehicle

logging:
  mapper-package: com.yz.mall.tw.vehicle.mapper

tw:
  vehicle:
    max-auth-users: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true