apiVersion: v1
kind: ConfigMap
metadata:
  name: rustfs-config
  namespace: mall
  labels:
    app.kubernetes.io/name: rustfs
    app.kubernetes.io/part-of: yz-mall
data:
  RUSTFS_VOLUMES: "/data"
  RUSTFS_ADDRESS: ":9000"
  RUSTFS_CONSOLE_ADDRESS: ":9001"
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
  RUSTFS_CORS_ALLOWED_ORIGINS: "*"
  RUSTFS_OBS_LOG_DIRECTORY: "/logs"
  RUSTFS_OBS_LOGGER_LEVEL: "info"
  RUSTFS_OBS_ENVIRONMENT: "development"
  RUSTFS_REGION: "us-east-1"
