networks:
  mall:
    driver: bridge

services:
  redis:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/redis:7.4.5
    container_name: 'redis-7.4.5'
    command: redis-server --requirepass "ss7Q22x"
    volumes:
      - C:\tools\docker\redis\config\redis.conf:/usr/local/etc/redis/redis.conf
      - C:\tools\docker\redis\data:/data
    ports:
      - '6379:6379'

  elasticsearch:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/elasticsearch:8.19.0
    container_name: 'elasticsearch-8.19.0'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ports:
      - '9200:9200'
      - '9300:9300'
    # 可选：设置重启策略（除非手动停止，否则在容器意外退出时都会自动重启）
    restart: unless-stopped
    mem_limit: 1536m
    networks:
      - mall

  kibana:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/kibana:8.19.0
    container_name: 'kibana-8.19.0'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - mall

  nacos:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/nacos-server:v2.5.1
    container_name: 'nacos-2.5.1'
    volumes:
      - C:\tools\docker\nacos\application.properties:/home/nacos/conf/application.properties
    ports:
      - '8848:8848'
      - '9848:9848'
      - '9849:9849'
    env_file:
      - C:\tools\docker\nacos\config.env
    networks:
      - mall

  rabbitmq:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/rabbitmq:3.13.7
    container_name: 'rabbitmq-3.13.7'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - mall