networks:
  mall:
    driver: bridge

services:
  redis:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/redis:7.4.5
    container_name: 'redis-7.4.5'
    command: redis-server --requirepass "ss7Q22x"
    volumes:
      - /opt/docker-dev-environment/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - /opt/docker-dev-environment/redis/data:/data
    ports:
      - '6379:6379'

  elasticsearch:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/elasticsearch:8.19.0
    container_name: 'elasticsearch-8.19.0'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - '9200:9200'
      - '9300:9300'
    # 可选：设置重启策略（除非手动停止，否则在容器意外退出时都会自动重启）
    restart: unless-stopped
    mem_limit: 1536m
    networks:
      - mall

  kibana:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/kibana:8.19.0
    container_name: 'kibana-8.19.0'
    environment:
      - ELASTICSEARCH_HOSTS=http://192.168.3.237:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - mall

  logstash:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/logstash:8.19.0
    container_name: 'logstash-8.19.0'
    ports:
      - '4560:4560'
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    volumes:
      - /opt/docker-dev-environment/logstash/mall-elk.conf:/usr/share/logstash/config/mall-elk.conf
      - /opt/docker-dev-environment/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    entrypoint:
      - logstash
      - -f
      - /usr/share/logstash/config/mall-elk.conf
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    networks:
      - mall

  nacos:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/nacos-server:v2.5.1
    container_name: 'nacos-2.5.1'
    volumes:
      - /opt/docker-dev-environment/nacos2.5.1/application.properties:/home/nacos/conf/application.properties
    ports:
      - '8848:8848'
      - '9848:9848'
      - '9849:9849'
    env_file:
      - /opt/docker-dev-environment/nacos2.5.1/config.env
    networks:
      - mall

  rabbitmq:
    image: registry.cn-guangzhou.aliyuncs.com/devyunze/rabbitmq:3.13.7
    container_name: 'rabbitmq-3.13.7'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - mall
