server:
  port: 26101

spring:
  application:
    name: mall-jaeger-a
  cloud:
    openfeign:
      micrometer:
        enabled: true

jaeger:
  b:
    url: http://192.168.3.20:26102

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  otlp:
    tracing:
      endpoint: ${JAEGER_OTLP_ENDPOINT:http://192.168.3.237:4318/v1/traces}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
