### 新增商品信息
POST http://localhost:30005/mall/product/add
Content-Type: application/json

{
  "name": "iPhone 14",
  "price": 4999,
  "title": "手机 苹果",
  "remark": "22年发布型号",
  "publishStatus": 1,
  "verifyStatus": 0,
  "albumPics": ""
}

### 商品详情
GET http://localhost:30005/mall/product/get/1802252777921855488

### 用户信息列表
POST http://localhost:30004/baseUser/page
Content-Type: application/json

{
  "filter": {

  }
}

### 新增订单数据
POST http://localhost:30006/omsOrder/add
Content-Type: application/json

{
  "userId": "1800559065600811008",
  "orderCode": "44010020240618000001",
  "orderType": 0,
  "totalAmount": 6500.50,
  "discountAmount": 200,
  "payAmount": 6300.5,
  "note": "快递不要放驿站",
  "receiverName": "张三",
  "receiverPhone": "15346646668",
  "receiverProvince": "440000000000",
  "receiverCity": "440100000000",
  "receiverRegion": "440106000000",
  "receiverAddress": "天河公园",
  "email": "834363368@qq.com"
}

### 新增订单详情数据
POST http://localhost:30006/omsOrderProductRelation/add
Content-Type: application/json

{
  "orderId": "1803071183313948672",
  "productId": "1802252777921855488",
  "productQuantity": 1,
  "discountAmount": 200,
  "realAmount": 6300.5,
  "productAttributes": "[{key:颜色,value:翡翠冷},{key:内存,value:16G}]"
}

### 生成订单
POST http://localhost:30006/omsOrder/generateOrder
Content-Type: application/json

{
  "userId": "1800559065600811008",
  "orderType": 0,
  "totalAmount": 4999.00,
  "discountAmount": 150,
  "payAmount": 4849,
  "note": "不要放驿站呀",
  "receiverName": "张三",
  "receiverPhone": "15346646668",
  "receiverProvince": "440000000000",
  "receiverCity": "440100000000",
  "receiverRegion": "440106000000",
  "receiverAddress": "五山地铁口",
  "email": "834363368@qq.com",
  "omsOrderItems": [
    {
      "productId": "1802364703359025152",
      "productQuantity": 1,
      "discountAmount": 150,
      "realAmount": 4849.00,
      "productAttributes": "[{key:颜色,value:紫色},{key:内存,value:4G}]"
    }
  ]
}

###
GET http://localhost:30004/baseUser/test/1

<> 2024-06-19T230735.200.json
<> 2024-06-19T230732.200.json

### 账户充值
POST http://localhost:30004/internal/baseUser/recharge
Content-Type: application/json

{
  "userId": "1800559065600811008",
  "amount": 3000
}


### 扣减余额
POST http://localhost:30004/baseUser/deduct
Content-Type: application/json

{
  "userId": "1800559065600811008",
  "amount": 100.052
}

<> 2024-06-19T232427.200.json

### 生成流水号
POST http://localhost:30008/internal/unqid/generateSerialNumber
Content-Type: application/json

{
  "prefix": "44010020240624",
  "numberLength": 6
}


### 批量生成流水号
POST http://localhost:30008/internal/unqid/generateSerialNumbers
Content-Type: application/json

{
  "prefix": "44010020240624",
  "numberLength": 6,
  "quantity": 5000
}


### 序列号生成
POST http://localhost:30008/internal/unqid/generateSerialNumber
Content-Type: application/json

{
  "prefix": "DEMO",
  "numberLength": 6,
  "quantity": 1
}



### 序列号生成-生产环境
POST http://159.75.135.41:30008/internal/unqid/generateSerialNumber
Content-Type: application/json

{
  "prefix": "DEMO",
  "numberLength": 6,
  "quantity": 1
}

<> 2024-07-05T003140.200.json
<> 2024-07-05T003124.200.json

### 流水号生成
POST http://localhost:30001/unqid/generateSerialNumber
Authorization: Bearer c1cf480fb8e74082a9f2e3928a1f1bea
Content-Type: application/json

{
  "prefix": "ABC"
}


### 登录系统
POST http://localhost:30001/login
Content-Type: application/json

{
  "username": "root",
  "password": "a1234567"
}

<> 2024-11-19T230707.200.json
<> 2024-11-19T211501.200.json
<> 2024-11-19T211420.200.json
<> 2024-11-19T211314.200.json


### 订单信息查询
POST http://localhost:30006/oms/order/page
Authorization: Bearer 66ae6c4a0c9a4b15add500c5b0aec527
Content-Type: application/json

{
  "filter": {

  }
}


### token刷新
POST http://localhost:30001/refreshToken
Content-Type: application/json

{
  "refreshToken": "48f2f3648c4549aabbb3005cba610b04",
  "userId": "root"
}

<> 2024-11-19T230758.200.json
<> 2024-11-19T230754.200.json
<> 2024-11-19T230744.200.json
<> 2024-11-19T230721.200.json


### 查询登录状态
GET http://localhost:30001/auth/isLogin
Authorization: Bearer c1cf480fb8e74082a9f2e3928a1f1bea


### 测试-登录
GET http://localhost:30006/login?username=root&password=a1234567

<> 2024-11-17T135909.200.txt
<> 2024-11-17T135832.500.html


### 测试-a
GET http://localhost:30006/a
Authorization: Bearer 7b115d71b0ce4e9b99125acdf47a705e

<> 2024-11-17T135926.200.txt




### 测试-b
GET http://localhost:30006/b
#Authorization: Bearer da7caa40860240d7851718e5d75e2103



### 测试-c
GET http://localhost:30006/c
Authorization: Bearer bfaf8611-e754-4ff4-a616-4381edcda5e7


### 测试-d
GET http://localhost:30006/d


### 系统-角色-新增
POST http://localhost:30004/sys/role/add
Content-Type: application/json

{
  "roleCode": "tourist",
  "roleName": "游客",
  "orgId": -1
}

<> 2024-11-17T190537.200.json
<> 2024-11-17T184125.200.json
<> 2024-11-17T183611.200.json
<> 2024-11-17T183051.404.json

### 系统-角色-分页查询
POST http://localhost:30004/sys/role/page
Content-Type: application/json

{
  "filter": {
    "roleCode": "",
    "roleName": "",
    "orgId": -1
  }
}

<> 2024-11-17T190544.200.json
<> 2024-11-17T190430.200.json
<> 2024-11-17T185917.200.json
<> 2024-11-17T185102.200.json
<> 2024-11-17T184322.200.json

### 系统-用户-新增
POST http://localhost:30004/sys/user/add
Content-Type: application/json

{
  "phone": "15346646669",
  "email": "834363368@qq.com",
  "password": "123456"
}

<> 2024-11-17T201609.200.json
<> 2024-11-17T194351.200.json

### 系统-用户-分页查询
POST http://localhost:30004/sys/user/page
Content-Type: application/json

{
  "filter": {
    "id": "",
    "createdTime": "",
    "phone": "",
    "email": ""
  }
}

<> 2024-11-18T211836.200.json
<> 2024-11-18T211434.200.json
<> 2024-11-18T211411.200.json
<> 2024-11-18T205607.200.json
<> 2024-11-18T194747.200.json
<> 2024-11-17T201616.200.json
<> 2024-11-17T195335.200.json

### 系统-角色关联-分页查询
POST http://localhost:30004/sys/role/relation/page
Content-Type: application/json

{
  "filter": {
    "id": 0,
    "createTime": "",
    "roleId": 0,
    "relationId": 0
  }
}

<> 2024-11-17T200348.200.json
<> 2024-11-17T195752.200.json

### 系统-角色关联-新增
POST http://localhost:30004/sys/role/relation/add
Content-Type: application/json

{
  "roleId": 1858104199268126720,
  "relationId": 1858121948841132032
}

<> 2024-11-17T201639.200.json
<> 2024-11-17T200325.200.json
<> 2024-11-17T200041.500.json
<> 2024-11-17T200022.500.json

### 系统-权限-分页查询
POST http://localhost:30004/sys/permission/page
Content-Type: application/json

{
  "filter": {
    "id": 0,
    "createTime": "",
    "permissionCode": "",
    "permissionName": "",
    "roleId": 0
  }
}

<> 2024-11-17T201513.200.json
<> 2024-11-17T201039.200.json

### 系统-权限-新增
POST http://localhost:30004/sys/permission/add
Content-Type: application/json

{
  "permissionCode": "sys:user:detail",
  "roleId": 1858104199268126720
}

<> 2024-11-17T201449.200.json

### 系统-组织-分页查询
POST http://localhost:30004/sys/org/page
Content-Type: application/json

{
  "filter": {
    "id": 0,
    "createTime": "",
    "orgName": "",
    "userId": 0
  }
}

<> 2024-11-17T202512.200.json
<> 2024-11-17T202037.404.json

### 系统-组织-新增
POST http://localhost:30004/sys/org/add
Content-Type: application/json

{
  "orgName": "系统开发者组织",
  "userId": 1858121948841132032
}

<> 2024-11-17T202508.200.json

### 系统-用户关联组织-分页查询
POST http://localhost:30004/sys/user/relation/org/page
Content-Type: application/json

{
  "filter": {
    "id": 0,
    "createTime": "",
    "userId": 0,
    "orgId": 0
  }
}

<> 2024-11-17T204032.200.json

### 系统-用户关联组织-新增
POST http://localhost:30004/sys/user/relation/org/add
Content-Type: application/json

{
  "userId": 1858121948841132032,
  "orgId": 1858124207599665152
}

<> 2024-11-17T203728.200.json
<> 2024-11-17T203229.500.json

### 系统-菜单-分页查询
POST http://localhost:30004/sys/menu/page
Content-Type: application/json

{
  "filter": {}
}

<> 2024-11-22T001115.200.json
<> 2024-11-22T001050.500.json
<> 2024-11-21T234135.200.json
<> 2024-11-21T234125.404.json
<> 2024-11-21T234058.404.json

### 系统-菜单-新增
POST http://localhost:30004/sys/menu/add
Content-Type: application/json

{
  "parentId": 0,
  "menuType": 0,
  "title": "menus.pureSysManagement",
  "name": "PureSystem",
  "path": "/system",
  "rank": 10,
  "icon": "ri:settings-3-line",
  "frameLoading": 1,
  "keepAlive": 0,
  "hiddenTag": 0,
  "fixedTag": 0,
  "showLink": 1,
  "showParent": 0
}

<> 2024-11-22T000428.500.json
<> 2024-11-22T000342.500.json
<> 2024-11-21T235952.500.json
<> 2024-11-21T235706.500.json