server:
  port: 10001

# 过滤器：URI 命中即做校验
sw:
  user-id-guard:
    enabled: true
    Uris:
      - /poc/test/**

spring:
  application:
    name: poc-sliding-window

# MyBatis Mapper SQL 调试包（供 logback-spring.xml 读取）
logging:
  mapper-package: com.yz.mall.poc.sw.mapper

app:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      Jedis:
        pool:
          max-active: 20
