
server:
  port: 25004

spring:
  application:
    name: mall-pms

# MyBatis Mapper SQL 调试包（供 logback-spring.xml 读取）
logging:
  mapper-package: com.yz.mall.pms.mapper

management:
  endpoints:
    web:
      exposure:
        include:  '*'